import { UmbrellaCert } from "@/types/certificate";

export const certificates: UmbrellaCert[] = [
  {
    id: "google-it-support-specialization",
    title: "Google IT Support Professional Certificate",
    issuer: "Google",
    category: "Infrastructure",
    date: "Aug – Dec 2025",
    thumbnail: "/certs/google.webp",
    description:
      "Comprehensive 6-course enterprise program covering computer networking, Linux and Windows systems administration, Active Directory integration, and IT security infrastructure.",
    skills: ["TCP/IP", "Active Directory", "Linux CLI", "DNS/DHCP", "SysAdmin"],
    credentialId: "149TSTLG1P7U",
    credentialUrl: "https://coursera.org/verify/professional-cert/149TSTLG1P7U",
    isSpecialization: true,
    status: "Completed",
    modules: [
      {
        id: "technical-support-fundamentals",
        title: "Technical Support Fundamentals",
        date: "Aug 2025",
        credentialId: "0RDHEIUBYOV3",
        credentialUrl: "https://coursera.org/verify/0RDHEIUBYOV3",
      },
      {
        id: "bits-and-bytes-computer-networking",
        title: "The Bits and Bytes of Computer Networking",
        date: "Sep 2025",
        credentialId: "TOVPDC6EK05A",
        credentialUrl: "https://coursera.org/verify/TOVPDC6EK05A",
      },
      {
        id: "operating-systems-power-user",
        title: "Operating Systems and You: Becoming a Power User",
        date: "Oct 2025",
        credentialId: "83G3DQUE1H7W",
        credentialUrl: "https://coursera.org/verify/83G3DQUE1H7W",
      },
      {
        id: "system-administration-it-infrastructure",
        title: "System Administration and IT Infrastructure Services",
        date: "Dec 2025",
        credentialId: "OYZ03BQCIR0V",
        credentialUrl: "https://coursera.org/verify/OYZ03BQCIR0V",
      },
      {
        id: "it-security-defense-digital-dark-arts",
        title: "IT Security: Defense Against the Digital Dark Arts",
        date: "Dec 2025",
        credentialId: "S1QQ5F1LFRGR",
        credentialUrl: "https://coursera.org/verify/S1QQ5F1LFRGR",
      },
    ],
  },
  {
    id: "applied-software-engineering-fundamentals",
    title: "Applied Software Engineering Fundamentals Specialization",
    issuer: "IBM",
    category: "Development",
    date: "Jul – Oct 2025",
    thumbnail: "/certs/ibm.webp",
    description:
      "5-course engineering specialization emphasizing Linux shell scripting, cron automated backups, Git version control, and Python development with REST API integrations.",
    skills: ["Bash Scripting", "Python", "Git", "Crontab", "REST APIs"],
    credentialId: "O5HVPSSOVJH1",
    credentialUrl: "https://coursera.org/verify/specialization/O5HVPSSOVJH1",
    isSpecialization: true,
    status: "Completed",
    modules: [
      {
        id: "intro-software-engineering-se",
        title: "Introduction to Software Engineering",
        date: "Jul 2025",
        credentialId: "J9F7NY1DFUWU",
        credentialUrl: "https://coursera.org/verify/J9F7NY1DFUWU",
      },
      {
        id: "getting-started-git-github-se",
        title: "Getting Started with Git and GitHub",
        date: "Jul 2025",
        credentialId: "GTMXEWTSTY0C",
        credentialUrl: "https://coursera.org/verify/GTMXEWTSTY0C",
      },
      {
        id: "linux-commands-shell-scripting",
        title: "Hands-on Introduction to Linux Commands and Shell Scripting",
        date: "Oct 2025",
        credentialId: "L2F1LG1Q2HK4",
        credentialUrl: "https://coursera.org/verify/L2F1LG1Q2HK4",
      },
      {
        id: "python-data-science-ai-development",
        title: "Python for Data Science, AI & Development",
        date: "Oct 2025",
        credentialId: "IZI2KWI0LY8N",
        credentialUrl: "https://coursera.org/verify/IZI2KWI0LY8N",
      },
      {
        id: "developing-ai-applications-python-flask",
        title: "Developing AI Applications with Python and Flask",
        date: "Oct 2025",
        credentialId: "NPCC3SILM930",
        credentialUrl: "https://coursera.org/verify/NPCC3SILM930",
      },
    ],
  },
  {
    id: "ibm-java-developer-suite",
    title: "IBM Java Developer Professional Track",
    issuer: "IBM & SkillUp",
    category: "Development",
    date: "Jul – Sep 2025",
    thumbnail: "/certs/ibm2.webp",
    description:
      "Completed the comprehensive 9-course core curriculum covering software engineering architecture, Java OOP, Spring Boot microservices, relational persistence (SQL & Hibernate), and Docker containerization.",
    skills: ["Java OOP", "Spring Boot", "Docker", "SQL/Hibernate", "CI/CD"],
    credentialId: null,
    credentialUrl: null,
    isSpecialization: true,
    status: "Completed",
    modules: [
      {
        id: "intro-software-engineering-java",
        title: "Introduction to Software Engineering",
        date: "Jul 2025",
        credentialId: "J9F7NY1DFUWU",
        credentialUrl: "https://coursera.org/verify/J9F7NY1DFUWU",
      },
      {
        id: "java-programming-beginners",
        title: "Java Programming for Beginners",
        date: "Jul 2025",
        credentialId: "VG6MQ523QTXA",
        credentialUrl: "https://coursera.org/verify/VG6MQ523QTXA",
      },
      {
        id: "getting-started-git-github-java",
        title: "Getting Started with Git and GitHub",
        date: "Jul 2025",
        credentialId: "GTMXEWTSTY0C",
        credentialUrl: "https://coursera.org/verify/GTMXEWTSTY0C",
      },
      {
        id: "oop-in-java",
        title: "Object Oriented Programming in Java",
        date: "Aug 2025",
        credentialId: "GKDPS4NOX0QX",
        credentialUrl: "https://coursera.org/verify/GKDPS4NOX0QX",
      },
      {
        id: "intro-html-css-javascript",
        title: "Introduction to HTML, CSS, & JavaScript",
        date: "Aug 2025",
        credentialId: "A6MKL74YC75F",
        credentialUrl: "https://coursera.org/verify/A6MKL74YC75F",
      },
      {
        id: "cloud-native-microservices-devops",
        title: "Cloud Native, Microservices, Containers, DevOps & Agile",
        date: "Aug 2025",
        credentialId: "G6AK17EELULT",
        credentialUrl: "https://coursera.org/verify/G6AK17EELULT",
      },
      {
        id: "spring-framework-java",
        title: "Spring Framework for Java Development",
        date: "Sep 2025",
        credentialId: "H4IW5U95X5WY",
        credentialUrl: "https://coursera.org/verify/H4IW5U95X5WY",
      },
      {
        id: "java-development-databases",
        title: "Java Development with Databases",
        date: "Sep 2025",
        credentialId: "LZEY73QUJXK0",
        credentialUrl: "https://coursera.org/verify/LZEY73QUJXK0",
      },
      {
        id: "java-app-dev-project",
        title: "Java App Development Project: Fundamentals, OOP & File I/O",
        date: "Sep 2025",
        credentialId: "UTYUAQRG90LN",
        credentialUrl: "https://coursera.org/verify/UTYUAQRG90LN",
      },
    ],
  },
  {
    id: "aws-cloud-technical-essentials",
    title: "AWS Cloud Technical Essentials",
    issuer: "Amazon Web Services",
    category: "Cloud",
    date: "Nov 2025",
    thumbnail: "/certs/aws.webp",
    description:
      "Foundational AWS architecture, IAM governance, compute instances (EC2, Lambda), object/block storage (S3), and CloudWatch telemetry monitoring.",
    skills: ["AWS S3", "IAM", "EC2", "CloudWatch", "Cloud Arch"],
    credentialId: "4SO81S20HL66",
    credentialUrl: "https://coursera.org/verify/4SO81S20HL66",
    isSpecialization: false,
    status: "Completed",
  },
  {
    id: "azure-data-non-relational",
    title: "Microsoft Azure Data: Non-Relational Cloud Storage",
    issuer: "Microsoft Learn",
    category: "Cloud",
    date: "Oct 2022",
    thumbnail: "/certs/microsoft.webp",
    description:
      "Architecting unstructured cloud storage solutions across Azure Blob stores, cloud file shares (SMB/NFS), and NoSQL architectures.",
    skills: ["Azure Blob", "Azure Files", "SMB/NFS", "Cosmos DB"],
    credentialId: "FR32QFLX",
    credentialUrl:
      "https://learn.microsoft.com/api/achievements/share/en-us/BonyKoshy-6243/FR32QFLX?sharingId=7CA1492B4874FC0E",
    isSpecialization: false,
    status: "Completed",
  },
  {
    id: "microsoft-power-platform-suite",
    title: "Microsoft Power Platform & Automation Suite",
    issuer: "Microsoft",
    category: "Productivity",
    date: "Oct 2022 – Feb 2026",
    thumbnail: "/certs/microsoft2.webp",
    description:
      "Enterprise low-code business solutions, automated operational workflows via Power Automate, and Dataverse table and environment administration.",
    skills: ["Power Automate", "Dataverse", "Power BI", "Power Apps"],
    credentialId: null,
    credentialUrl: null,
    isSpecialization: true,
    status: "Completed",
    modules: [
      {
        id: "pl-900-power-platform-fundamentals",
        title: "PL-900: Microsoft Power Platform Fundamentals (Trophy)",
        date: "Oct 2022",
        credentialId: "NA3EVVPF",
        credentialUrl:
          "https://learn.microsoft.com/api/achievements/share/en-us/BonyKoshy-6243/NA3EVVPF?sharingId=7CA1492B4874FC0E",
      },
      {
        id: "intro-microsoft-power-platform-coursera",
        title: "Introduction to Microsoft Power Platform (Coursera)",
        date: "Feb 2026",
        credentialId: "C7EEKNTZ5UIU",
        credentialUrl: "https://coursera.org/verify/C7EEKNTZ5UIU",
      },
    ],
  },
  {
    id: "full-stack-python-vap",
    title: "Full-Stack Development with Python (VAP)",
    issuer: "CMS College & TrendUp",
    category: "Development",
    date: "Dec 2024",
    thumbnail: "/certs/cms.webp",
    description:
      "Intensive value-added certification in Python backend scripting, web application architectures, database operations, and task automation.",
    skills: ["Python", "Backend Web", "Databases", "Automation"],
    credentialId: "22BCA009",
    credentialUrl: "https://cmscbe.com",
    isSpecialization: false,
    status: "Completed",
  },
  {
    id: "infosys-soft-skills-program",
    title: "Soft Skills Corporate Development Program",
    issuer: "Infosys BPM",
    category: "Productivity",
    date: "Aug 2024",
    thumbnail: "/certs/infosys.webp",
    description:
      "Corporate readiness program covering structured business communication, client-facing etiquette, cross-functional collaboration, and professional stakeholder management.",
    skills: ["Communication", "Client Relations", "Cross-Functional"],
    credentialId: null,
    credentialUrl: "https://www.infosysbpm.com",
    isSpecialization: false,
    status: "Completed",
  },
];
